# Generated by Django 2.2 on 2020-12-21 03:25

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='User ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='User Avatar')),
                ('gender', models.BooleanField(choices=[('M', 'Male'), ('F', 'Female')], default=True, verbose_name='Gender')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Designer', 'Designer'), ('Customer', 'Customer')], default='Customer', max_length=10, verbose_name='User Type')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AqutousCoating',
            fields=[
                ('aqutous_coating_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Aqutous Coating ID')),
                ('aqutous_coating_type', models.CharField(max_length=30, verbose_name='Aqutous Coating Type')),
            ],
        ),
        migrations.CreateModel(
            name='BindingMethod',
            fields=[
                ('binding_method_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Binding Method ID')),
                ('binding_methods', models.CharField(max_length=30, verbose_name='Binding Methods')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Color ID')),
                ('prod_color', models.CharField(max_length=50, verbose_name='Product Color')),
            ],
        ),
        migrations.CreateModel(
            name='FoldingOptions',
            fields=[
                ('folding_options_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Folding Options ID')),
                ('folding_options_type', models.CharField(max_length=30, verbose_name='Folding Options Types')),
            ],
        ),
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Image ID')),
                ('img_path', models.ImageField(default='', upload_to='', verbose_name='Image Path')),
                ('upload_date', models.DateField(auto_now_add=True, verbose_name='Image Upload Date')),
            ],
        ),
        migrations.CreateModel(
            name='HoleDrilling',
            fields=[
                ('hole_drilling_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Hole Drilling ID')),
                ('hole', models.BooleanField(default=False, verbose_name='Hole Drilling')),
            ],
        ),
        migrations.CreateModel(
            name='ImageTemplate',
            fields=[
                ('temp_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Template ID')),
                ('temp_img', models.ImageField(upload_to='Template Images/', verbose_name='Template Image')),
            ],
        ),
        migrations.CreateModel(
            name='NoOfMonths',
            fields=[
                ('no_of_months_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='No Of Months ID')),
                ('months', models.CharField(max_length=15, verbose_name='No of Months')),
            ],
        ),
        migrations.CreateModel(
            name='PaperChoice',
            fields=[
                ('paper_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Paper Choice ID')),
                ('paper_choices_name', models.CharField(max_length=50, verbose_name='Paper Choices')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Product ID')),
                ('prod_Name', models.CharField(max_length=30, verbose_name='Product Name')),
                ('prod_Desc', models.CharField(max_length=2000, verbose_name='Product Description')),
                ('prod_Price', models.IntegerField(default=0.0, verbose_name='Product Price/Piece')),
                ('prod_img', models.ImageField(null=True, upload_to='productImage/', verbose_name='Product Image')),
            ],
        ),
        migrations.CreateModel(
            name='ShrinkWrapping',
            fields=[
                ('shrink_wrapping_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Shrink Wrapping ID')),
                ('shrink_options', models.CharField(max_length=20, verbose_name='Shrink Wrap Options')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('size_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Size ID')),
                ('prod_size', models.CharField(max_length=20, verbose_name='Product Size')),
            ],
        ),
        migrations.CreateModel(
            name='SizeProductMapping',
            fields=[
                ('size_p_map_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Size & Product Map ID')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Product', verbose_name='Product Id')),
                ('size_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Size', verbose_name='Size ID')),
            ],
        ),
        migrations.CreateModel(
            name='ShrinkWrappingProductMapping',
            fields=[
                ('shrink_wrap_p_map_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Shrink Wrapping & Product Map ID')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Product', verbose_name='Product Id')),
                ('shrink_wrapping_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ShrinkWrapping', verbose_name='Shrink Wrapping ID')),
            ],
        ),
        migrations.CreateModel(
            name='PaperChoiceProductMapping',
            fields=[
                ('paper_p_map_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Paper Choices & Product Map ID')),
                ('paper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.PaperChoice', verbose_name='Paper ID')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Product', verbose_name='Product Id')),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('package_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Package ID')),
                ('package_Name', models.CharField(max_length=30, verbose_name='Package Name')),
                ('attribute_values', models.CharField(max_length=200, verbose_name='Item Details JSON')),
                ('package_Price', models.IntegerField(default=0.0, verbose_name='Package Price')),
                ('prod_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Product', verbose_name='Product ID (FK)')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Order ID')),
                ('quantity', models.ImageField(default=500, max_length=10, upload_to='', verbose_name='Product Quantity')),
                ('attribute_value', models.CharField(max_length=2000, verbose_name='Item Details JSON')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='Order Date')),
                ('order_job_title', models.CharField(max_length=100, verbose_name='Name of Company/Business')),
                ('order_desc', models.CharField(max_length=1000, verbose_name='Details for Product')),
                ('product_img', models.ImageField(upload_to='', verbose_name='Template Image')),
                ('address', models.CharField(max_length=100, verbose_name='Customer Address ')),
                ('state', models.CharField(max_length=30, verbose_name='Customer State')),
                ('city', models.CharField(max_length=30, verbose_name='Customer City')),
                ('postal_code', models.IntegerField(verbose_name='Area Pin Code')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Product', verbose_name='Product ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer ID')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notify_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('notify_detail', models.CharField(max_length=200, verbose_name='Notification Detail')),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Order', verbose_name='Order ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID')),
            ],
        ),
        migrations.CreateModel(
            name='NoOfMonthsProductMapping',
            fields=[
                ('no_of_months_p_map_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='No Of Months & Product Map ID')),
                ('no_of_months_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.NoOfMonths', verbose_name='No Of Months ID')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Product', verbose_name='Product Id')),
            ],
        ),
        migrations.CreateModel(
            name='ImageTemplateProductMapping',
            fields=[
                ('imageTemp_p_map_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Template Image & Product Map ID')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Product', verbose_name='Product Id')),
                ('temp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ImageTemplate', verbose_name='Image Template ID')),
            ],
        ),
        migrations.CreateModel(
            name='HoleDrillingProductMapping',
            fields=[
                ('hole_drill_p_map_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Hole Drilling & Product Map ID')),
                ('hole_drilling_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.HoleDrilling', verbose_name='Hole Drilling ID')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Product', verbose_name='Product Id')),
            ],
        ),
        migrations.CreateModel(
            name='FoldingOptionsProductMapping',
            fields=[
                ('folding_option_p_map_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Folding Options & Product Map ID')),
                ('folding_options_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.FoldingOptions', verbose_name='Folding Options ID')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Product', verbose_name='Product Id')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False, verbose_name='FeedBack ID')),
                ('feedback_desc', models.CharField(max_length=300, verbose_name='Customer FeedBack')),
                ('feedback_date', models.DateField(auto_now_add=True, verbose_name='FeedBack Date ')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer ID')),
            ],
        ),
        migrations.CreateModel(
            name='ColorProductMapping',
            fields=[
                ('color_p_map_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Color & Product Map ID')),
                ('color_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Color', verbose_name='Color ID')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Product', verbose_name='Product Id')),
            ],
        ),
        migrations.CreateModel(
            name='BindingMethodProductMapping',
            fields=[
                ('binding_methods_p_map_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Binding Method & Product Map ID')),
                ('binding_method_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.BindingMethod', verbose_name='Binding Methods ID')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Product', verbose_name='Product Id')),
            ],
        ),
        migrations.CreateModel(
            name='AqutousCoatingProductMapping',
            fields=[
                ('aCoat_p_map_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Aqutous Coating & Product Map ID')),
                ('aqutous_coating_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.AqutousCoating', verbose_name='Aqutous Coating ID')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Product', verbose_name='Product Id')),
            ],
        ),
    ]
