# Generated by Django 3.1.2 on 2020-12-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetemplate',
            name='temp_img',
            field=models.ImageField(upload_to='', verbose_name='Template Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_img',
            field=models.ImageField(null=True, upload_to='', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='User Avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
