# Generated by Django 3.1.5 on 2021-02-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='Customer Address'),
        ),
    ]
