# Generated by Django 3.1.5 on 2021-02-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='attribute_values',
            field=models.CharField(max_length=500, verbose_name='Item Details JSON'),
        ),
    ]
