# Generated by Django 3.1.5 on 2021-03-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210228_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
        ),
    ]
