# Generated by Django 3.1.2 on 2021-01-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201221_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_Price',
            field=models.FloatField(default=0.0, verbose_name='Product Price/Piece'),
        ),
    ]
