# Generated by Django 3.1.5 on 2021-03-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_packages_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default-user-img.png', null=True, upload_to='', verbose_name='User Avatar'),
        ),
    ]
