# Generated by Django 3.1.5 on 2021-03-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210305_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='attribute_values',
            field=models.JSONField(max_length=500, verbose_name='Item Details JSON'),
        ),
    ]
