# Generated by Django 3.1.5 on 2021-01-31 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_order_order_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pay_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Payment ID')),
                ('pay_date', models.DateField(auto_now_add=True, verbose_name='Payment Date')),
                ('pay_status', models.CharField(choices=[('P', 'Paid'), ('U', 'Unpaid')], default='U', max_length=20, verbose_name='Payment Status')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.order', verbose_name='Order Id')),
            ],
        ),
    ]
