# Generated by Django 3.1.5 on 2021-02-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210212_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0, max_length=10, verbose_name='Product Quantity'),
        ),
    ]
